#!/usr/bin/env python3
"""Sync the repository README into the MkDocs homepage.

MkDocs only builds files that live under the docs directory, so the site
homepage is generated by copying README.md to docs/index.md and rewriting
repo-relative doc links into site-relative links.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
README = ROOT / "README.md"
OUT = ROOT / "docs" / "index.md"

text = README.read_text(encoding="utf-8")

# "docs/extending-the-library.md" (valid on GitHub) -> "extending-the-library.md"
# (valid on the built site, where docs/ is the site root).
text = text.replace("](docs/", "](")

OUT.write_text(text, encoding="utf-8", newline="\n")
print(f"Wrote {OUT.relative_to(ROOT)} ({len(text)} chars) from {README.name}")
